# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: crossings
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
DATABASE:
  URL: ${DATABASE_URL}
  OPTIONS: {
    dialectOptions: {
      ssl: {
          require: true,
          rejectUnauthorized: true
      }
    }
  }
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
UNIVERSAL_LINKS:
  # This should be your app's bundle ID, as found in your info.plist.
  APPLE_APP_ID: church.crossings.rock
  # This should be your app's team ID, as found in Xcode
  APPLE_TEAM_ID: 83DP3WM45E
  # Where should a user be redirected if they don't have your app installed?
  APP_STORE_LINK: https://apps.apple.com/us/app/crossings-church-new/id1501893128
  PLAY_STORE_LINK: https://crossings.church/app
  # Your app Id, as found in your app/build.gradle.
  GOOGLE_APP_ID: church.crossings.rockapp
  # https://docs.getsocial.im/knowledge-base/android-signing-key-sha256/
  GOOGLE_KEYSTORE_SHA256: 1C:22:BD:84:1E:5D:FB:BC:C3:54:27:AB:0D:D0:D7:16:B4:17:4C:0B:1A:7A:DF:CA:FB:A5:3E:1F:EB:85:3A:AD
ONE_SIGNAL:
  APP_ID: 144c1d64-5745-429c-8c50-3c45891711cd
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: https://venue.online.church/
  WEB_VIEW_URL: https://venue.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
  SEARCH_INDEX: ${ALGOLIASEARCH_INDEX}
  # Configure Algolia custom settings here
  # https://www.algolia.com/doc/api-reference/settings-api-parameters/
  CONFIGURATION:
    searchableAttributes:
      - title
      - htmlContent
      - unordered(summary)
      - author
      - tags
    #customRankings:
    # NOT CURRENTLY INCLUDED
    # This just demonstrates what's possible
    # To include likedCount (or any other field) override search package
    # and add field to config below
    #- desc(likedCount)
CLEARSTREAM:
  API_KEY: ${CLEARSTREAM_API_KEY}
  FROM_NUMBER: ${CLEARSTREAM_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
ANALYTICS:
  # Filling out these fields will automatically enable analytics tracking
  # on the accompanying service
  SEGMENT_KEY:
  GA_ID:
  USE_ROCK: false
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    KJV: 'de4e12af7f28f599-01'
    
CLOUDINARY:
  # Cloudinary is used to improve image loading
  # value should look something like
  # cloudinary://123123123:adkfnla_adASDv_adAS@test
  URL: ${CLOUDINARY_URL}
ENGINE:
  API_KEY: ${APOLLO_KEY}
  SCHEMA_TAG: ${ENGINE_SCHEMA_TAG}

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  INTERACTIONS:
    # Name of the InteractionChannel that will be created per EntityType
    CHANNEL_NAME: Apollos Crossings App
    # Prefix for the name of the InteractionComponent that will be created per Entity
    COMPONENT_NAME: Apollos Crossings App Component
    # 512 is "Mobile App"
    CHANNEL_MEDIUM_TYPE_ID: 512

  CONTENT_ITEM:
    ContentSeriesContentItem:
      # When resolving "ContentSeriesContentItem" look in rock for a "ContentChannelItem"
      EntityType: ContentChannelItem
      # Used to define the subset of content channels types that use this specific type.
      ContentChannelTypeId: [6, 11]
    DevotionalContentItem:
      EntityType: ContentChannelItem
      ContentChannelTypeId: [12]
    MediaContentItem:
      EntityType: ContentChannelItem
    UniversalContentItem:
      EntityType: ContentChannelItem
    WeekendContentItem:
      ContentChannelId: [21]
      EntityType: ContentChannelItem
    LiveContentItem:
      ContentChannelTypeId: [156]
      EntityType: ContentChannelItem
    ContentItem:
      EntityType: ContentChannelItem

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 498

  # Todo add events to be returnable type 
  SEARCH_CONTENT_CHANNEL_IDS:
    - f88d88d6-33d2-4189-9484-a94cb5164f41
    - a220055c-31c9-4e46-baf6-493b5ce45985
    - dc7d5f6e-b0f8-4e01-9b4a-3fde325a1d83
    - 8260787d-cada-453a-91c0-4f0ede534d53

  ALL_CONTENT_CHANNELS:
    - f88d88d6-33d2-4189-9484-a94cb5164f41
    - a220055c-31c9-4e46-baf6-493b5ce45985
    - 8260787d-cada-453a-91c0-4f0ede534d53

  ALL_CALIDS:
    - 4
    - 3
    - 1
    - 5
    - 6
    
  SERMON_CHANNEL_ID: f88d88d6-33d2-4189-9484-a94cb5164f41

  SERVING_GROUP_TYPE_ID: 23
  COMMUNITY_GROUP_TYPE_ID: 25
  FAMILY_GROUP_TYPE_ID: 10

  MOBILE_DEVICE_TYPE_ID: 671

  SUNDAY_SERMON_SCHEDULE_CATEGORY_ID: 406

  LIVESTREAM_CONTENT_CHANNEL_ID: 443
  LIVESTREAM_EVENT_CONTENT_CHANNEL_ID: 588

TABS:
  HOME:
    - type: ActionBar
      actions: [{
        title: Check In,
        icon: check,
        id: 123456789,
        action: OPEN_AUTHENTICATED_URL,
        relatedNode: {
          __typename: Url,
          url: 'https://crossings.church/self-checkin',
        }
      },
      {
        title: Give,
        icon: hands,
        id: 1234,
        action: OPEN_URL,
        relatedNode: {
          __typename: Url,
          url: 'https://crossings.church/give'
        },
      }]
    - algorithms: [UPCOMING_STREAMS]
      type: LiveContentList
      title: Live Now
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - f88d88d6-33d2-4189-9484-a94cb5164f41
          limit: 5
      type: HeroList
      title: Recent Sermons
    #- algorithms: [CONTENT_CHANNEL]
    #  contentChannelId: 19
    #  title: Teaching Series
    #  subtitle: Weekly Teachings
    #  type: HorizontalCardList
    #  limit: 5
    #  primaryAction:
    #    action: OPEN_CHANNEL
    #    title: See More
    #    relatedNode:
    #      __typename: ContentChannel
    #      id: 19
    #- algorithms: [CONTENT_CHANNEL]
    #  contentChannelId: 23
    #  title: Devotions
    #  subtitle: Weekly Studies
    #  type: HorizontalCardList
    #  limit: 5
    #  primaryAction:
    #    action: OPEN_CHANNEL
    #    title: See More
    #    relatedNode:
    #      __typename: ContentChannel
    #      id: 23
    - title: Upcoming Events
      subtitle: What's happening at Crossings
      type: ActionList
      algorithms:
        - type: UPCOMING_EVENTS
    - title: FOR YOU
      algorithms: [SERMON_CHILDREN, PERSONA_FEED]
      subtitle: Explore what God calls you to today
      type: ActionList
    - algorithms: [PERSONA_FEED]
      subtitle: Continue
      type: HorizontalCardList
    - title: RECOMMENDED
      algorithms: [SERMON_CHILDREN]
      subtitle: For Him
      type: VerticalCardList
#NEED TO NAIL DOWN WHAT TO SHOW HERE.  
  READ:
      - algorithms:
          - type: CONTENT_FEED
            arguments:
              channelIds:
                - 8260787d-cada-453a-91c0-4f0ede534d53
              limit: 5
        type: HorizontalCardList
        subtitle: Devotionals
        primaryAction:
          action: OPEN_CHANNEL
          title: 'Read More'
          relatedNode:
            __typename: ContentChannel
            id: 8260787d-cada-453a-91c0-4f0ede534d53
            name: Devotionals
  
  WATCH:
      - algorithms:
          - type: LATEST_SERIES_CHILDREN
            arguments:
              channelId: e848a74f-d2d9-4dcf-824c-373fe0db4327
        type: HeroList
        title: Catch up
        subtitle: Latest Sermons
    #need to limit this one to not show all existing sermon series and to point to the read more action
      - algorithms:
          - type: CONTENT_FEED
            arguments:
              channelIds:
                - e848a74f-d2d9-4dcf-824c-373fe0db4327
              limit: 6
        type: HorizontalCardList
        subtitle: All Sermon Series
        primaryAction:
          action: OPEN_CHANNEL
          title: See More
          relatedNode:
            __typename: ContentChannel
            id: e848a74f-d2d9-4dcf-824c-373fe0db4327
      - algorithms:
          - type: CONTENT_FEED
            arguments:
              channelIds:
                - 85d16d40-4485-41cb-91fe-180ec06c83b6
                - 42a4f1cf0-61fd-4231-9592-ea1b076e1bc2
              limit: 4
        type: HorizontalCardList
        subtitle: Latest Teaching Series
      #- algorithms:
      #    - type: CONTENT_FEED
      #      arguments:
      #        channelIds:
      #          - 19
      #          - 422
      #        limit: 
      #  type: HorizontalCardList
      #  subtitle: Podcasts
      #  primaryAction:
      #    action: OPEN_CHANNEL
      #    title: 'Read More'
      #    relatedNode:
      #      __typename: ContentChannel
      #      id: 5
      #      name: Podcasts
      #- algorithms:
      #    - type: CONTENT_FEED
      #      arguments:
      #        channelIds:
      #          - 6
      #        limit: 3
      #  type: HorizontalCardList
      #  title: Videos
      #  primaryAction:
      #    action: OPEN_CHANNEL
      #    title: 'Read More'
      #    relatedNode:
      #      __typename: ContentChannel
      #      id: 6
      #      name: Videos
      #- algorithms:
      #    - type: CONTENT_FEED
      #      arguments:
      #        channelIds:
      #          - 8
      #        limit: 3
      #  type: HorizontalCardList
      #  subtitle: Something Else

  PRAY:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    - type: VerticalPrayerList
      title: Your Prayers
  CONNECT:
    - type: ActionTable
      title: Connect to Apollos
      actions:
        [
          {
            title: Google,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.google.com' },
          },
          {
            title: Facebook,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.facebook.com' },
          },
        ]