# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ${DEEP_LINK_HOST}
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
DATABASE:
  URL: ${DATABASE_URL}
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
UNIVERSAL_LINKS:
  APPLE_APP_ID: ${APPLE_APP_ID}
  APPLE_TEAM_ID: ${APPLE_TEAM_ID}
  APP_STORE_LINK: ${IOS_REDIRECT}
  PLAY_STORE_LINK: ${ANDROID_REDIRECT}
  GOOGLE_APP_ID: ${GOOGLE_APP_ID}
  GOOGLE_KEYSTORE_SHA256: ${GOOGLE_KEYSTORE_SHA256}
ONE_SIGNAL:
  APP_ID: ${ONE_SIGNAL_APP_ID}
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: ${CHURCH_ONLINE_URL}
  WEB_VIEW_URL: https://apollos.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    WEB: '9879dbb7cfe39e4d-01'
    KJV: 'de4e12af7f28f599-02'
CLOUDINARY:
  URL: ${CLOUDINARY_URL}

CONTENT:
  SERMON_CHANNEL_ID: f8b05204-f99c-4f40-93c3-0f4726d0b265
  TYPES:
    - ContentSeriesContentItem
    - DevotionalContentItem
    - MediaContentItem
    - UniversalContentItem
    - WeekendContentItem
    - ContentItem

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 498

  # Todo add events to be returnable type 
  SEARCH_CONTENT_CHANNEL_IDS:
    - f8b05204-f99c-4f40-93c3-0f4726d0b265
    - 592e144b-6735-4604-9c0a-df81a623d411
    - 531d3fea-10a1-4ee4-86da-fbba0a09562a
    - a83fe07f-06ce-477e-956a-d95ce088dce6

  ALL_CONTENT_CHANNELS:
    - f8b05204-f99c-4f40-93c3-0f4726d0b265
    - 592e144b-6735-4604-9c0a-df81a623d411
    - 531d3fea-10a1-4ee4-86da-fbba0a09562a

  ALL_CALIDS:
    - 4
    - 3
    - 1
    - 5
    - 6
    
 

  SERVING_GROUP_TYPE_ID: 23
  COMMUNITY_GROUP_TYPE_ID: 25
  FAMILY_GROUP_TYPE_ID: 10

  MOBILE_DEVICE_TYPE_ID: 671

  SUNDAY_SERMON_SCHEDULE_CATEGORY_ID: 406

  LIVESTREAM_CONTENT_CHANNEL_ID: 443
  LIVESTREAM_EVENT_CONTENT_CHANNEL_ID: 588

TABS:
  HOME:
    - type: ActionBar
      actions: [{
        title: Check In,
        icon: check,
        id: 123456789,
        action: OPEN_AUTHENTICATED_URL,
        relatedNode: {
          __typename: Url,
          url: 'https://crossings.church/self-checkin',
        }
      },
      {
        title: Give,
        icon: hands,
        id: 1234,
        action: OPEN_URL,
        relatedNode: {
          __typename: Url,
          url: 'https://crossings.church/give'
        },
      }]
    #- algorithms: [UPCOMING_STREAMS]
    #  type: LiveContentList
    #  title: Live Now
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - f8b05204-f99c-4f40-93c3-0f4726d0b265
          limit: 5
      type: HeroList
      title: Recent Sermons
    #- algorithms: [CONTENT_CHANNEL]
    #  contentChannelId: 19
    #  title: Teaching Series
    #  subtitle: Weekly Teachings
    #  type: HorizontalCardList
    #  limit: 5
    #  primaryAction:
    #    action: OPEN_CHANNEL
    #    title: See More
    #    relatedNode:
    #      __typename: ContentChannel
    #      id: 19
    #- algorithms: [CONTENT_CHANNEL]
    #  contentChannelId: 23
    #  title: Devotions
    #  subtitle: Weekly Studies
    #  type: HorizontalCardList
    #  limit: 5
    #  primaryAction:
    #    action: OPEN_CHANNEL
    #    title: See More
    #    relatedNode:
    #      __typename: ContentChannel
    #      id: 23
    - title: Upcoming Events
      subtitle: What's happening at Crossings
      type: ActionList
      algorithms:
        - type: UPCOMING_EVENTS
    - title: FOR YOU
      algorithms: [SERMON_CHILDREN, PERSONA_FEED]
      subtitle: Explore what God calls you to today
      type: ActionList
    - algorithms: [PERSONA_FEED]
      subtitle: Continue
      type: HorizontalCardList
    - title: RECOMMENDED
      algorithms: [SERMON_CHILDREN]
      subtitle: For Him
      type: VerticalCardList
#NEED TO NAIL DOWN WHAT TO SHOW HERE.  
  READ:
      - algorithms:
          - type: CONTENT_FEED
            arguments:
              channelIds:
                - a83fe07f-06ce-477e-956a-d95ce088dce6
              limit: 5
        type: HorizontalCardList
        subtitle: Devotionals
        primaryAction:
          action: OPEN_CHANNEL
          title: 'Read More'
          relatedNode:
            __typename: ContentChannel
            apollosId: ContentChannela83fe07f-06ce-477e-956a-d95ce088dce6
            name: Devotionals
  
  WATCH:
      - algorithms:
          - type: LATEST_SERIES_CHILDREN
            arguments:
              channelId: f8b05204-f99c-4f40-93c3-0f4726d0b265
        type: HeroList
        title: Catch up
        subtitle: Latest Sermons
    #need to limit this one to not show all existing sermon series and to point to the read more action
      - algorithms:
          - type: CONTENT_FEED
            arguments:
              channelIds:
                - b5a7b930-7924-46a3-8365-e449abe8e644
              limit: 6
        type: HorizontalCardList
        subtitle: All Sermon Series
        primaryAction:
          action: OPEN_CHANNEL
          title: See More
          relatedNode:
            __typename: ContentChannel
            apollosId: ContentChannelb5a7b930-7924-46a3-8365-e449abe8e644
      - algorithms:
          - type: CONTENT_FEED
            arguments:
              channelIds:
                - 067ad7bd-26c1-4f67-b950-d6bcdcd2f5e8
                - 955ed0f8-03f6-4f0b-b48e-b095e9bf6000
              limit: 4
        type: HorizontalCardList
        subtitle: Latest Teaching Series
      #- algorithms:
      #    - type: CONTENT_FEED
      #      arguments:
      #        channelIds:
      #          - 19
      #          - 422
      #        limit: 
      #  type: HorizontalCardList
      #  subtitle: Podcasts
      #  primaryAction:
      #    action: OPEN_CHANNEL
      #    title: 'Read More'
      #    relatedNode:
      #      __typename: ContentChannel
      #      id: 5
      #      name: Podcasts
      #- algorithms:
      #    - type: CONTENT_FEED
      #      arguments:
      #        channelIds:
      #          - 6
      #        limit: 3
      #  type: HorizontalCardList
      #  title: Videos
      #  primaryAction:
      #    action: OPEN_CHANNEL
      #    title: 'Read More'
      #    relatedNode:
      #      __typename: ContentChannel
      #      id: 6
      #      name: Videos
      #- algorithms:
      #    - type: CONTENT_FEED
      #      arguments:
      #        channelIds:
      #          - 8
      #        limit: 3
      #  type: HorizontalCardList
      #  subtitle: Something Else

  PRAY:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    - type: VerticalPrayerList
      title: Your Prayers
  CONNECT:
    - type: ActionTable
      title: Connect to Apollos
      actions:
        [
          {
            title: Google,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.google.com' },
          },
          {
            title: Facebook,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.facebook.com' },
          },
        ]