# This workflow will use Fastly to build and push IOS and Android mobile apps
# it will only run when something changes in the .apolloschurchapp folder
#
# To use this workflow, you will need to complete the following set-up steps:
#

on:
  push:
    branches:
      - master

name: build and deploy IOS

jobs:
  ios:
    defaults:
      run:
        working-directory: apolloschurchapp

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check For App Changes
        run: if [[ $(git diff HEAD ../apolloschurchapp/) == "" ]]; then exit 1; fi

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Bundler
        run: gem install bundler

      - name: Decrypt Environment Variables and Apple API Key
        run: (npx @apollosproject/apollos-cli secrets -d ${{ secrets.ENCRYPTION_PASSWORD }})

      - run: cp .env.shared .env

      - name: Install Dependencies
        run: yarn

      # required to build
      - name: Generate Stories
        run: yarn generate-stories

      - name: Generate Fragment Types
        run: node ./scripts/get-introspection-data.js
        env:
          APP_DATA_URL: ${{ secrets.APP_DATA_URL }}

      - name: Fastlane Deploy
        run: bundle exec fastlane ios deploy
